### ISSUE TITLE
Should delete empty workspace when closing a fullscreen app

### ISSUE THREAD

**Issue by DarwinAwardWinner** [satran/fullscreenworkspace-satran.in#10]
In general this extension works great, but the one missing edge case I can see is that if you directly close an app that is currently fullscreen on its own workspace, then you are left with an empty workspace. I think that if the workspace is empty after closing an app that was in fullscreen mode, the extension should delete that workspace.

**Comment by satran** [comment]
@DarwinAwardWinner thanks for that. I think that could be considered as a bug. Let me see if I can plug into the close event.

**Comment by florentdescroix** [comment]
@satran I've noticed the same issue, so I changed the `unmaximize` as followed 
```
function unmaximize(act){
    const win = act.meta_window;
    if (win.window_type !== Meta.WindowType.NORMAL)
    	return;
    let previous = _previousWorkspace[win.toString()];
    if (previous == null || previous == undefined)
	    return;
    // Here
    delete _previousWorkspace[win.toString()];
    win.change_workspace_by_index(previous, 1);
    // Here
    let fullScreenWorkspace = global.workspace_manager.get_active_workspace();
    global.workspace_manager.get_workspace_by_index(previous).activate(global.get_current_time());
    // Here
    global.workspaceManager.remove_workspace(fullScreenWorkspace);
}
```
I took the opportunity to also clean the `_previousWorkspace` object.

**Comment by DarwinAwardWinner** [comment]
@florentdescroix I think you might be talking about a different issue. This issue is about what happens when you quit a fullscreen app, not when you unmaximize it.

**Comment by florentdescroix** [comment]
@DarwinAwardWinner ho right ! Well at least that's here ^^

**Comment by satran** [comment]
@florentdescroix  thanks. I have added your changes, much appreciated.
