### ISSUE TITLE
There is alway an empty workspace before the full screen one

### ISSUE THREAD

**Issue by florentdescroix** [satran/fullscreenworkspace-satran.in#11]
I noticed that I always had an empty workspace before the full screen one, which is not actually a big issue, but is useless.

As I understood Gnome-shell functioning, there is always an empty workspace at the end of the line, waiting for new windows. 
So the full screen window should go there and not on another new workspace.

What I did to fix it was changing the line 14 of the `extension.js` file like that :
`let lastworkspace = global.workspace_manager.n_workspaces-1;`

And voila :)

**Comment by satran** [comment]
Thanks for that. I will try to incorporate it.

**Comment by dipunm** [comment]
+1, I made this change manually for myself. Looking forward to the next release :)
