### ISSUE TITLE
On dual monitor I get this error: this._indicator is undefined

### ISSUE THREAD

**Issue by AI-ien** [satran/fullscreenworkspace-satran.in#13]
![image](https://user-images.githubusercontent.com/33252703/148505375-878409a1-c6cf-4b56-810a-b30e807ae772.png)

OS: Fedora 35
Gnome: 41.2
Windows: Wayland

**Comment by satran** [comment]
This is fixed by the commit, the extension will be updated shortly in gnome-extensions. @AI-ien thanks for filing the bug.
