### ISSUE TITLE
this._indicator is undefined

### ISSUE THREAD

**Issue by Tygrain** [satran/fullscreenworkspace-satran.in#16]
On my system(Fedora 35, Wayland GNOME 41.3) the extension fails with an error ` this._indicator is undefined`
![Screenshot](https://user-images.githubusercontent.com/50624811/153784016-3d8203aa-a0ca-4e60-98bc-75ab56f40726.png)

**Comment by satran** [comment]
This is fixed by the commit, the extension will be updated shortly in gnome-extensions. @Tygrain thanks for filing the bug.
