### ISSUE TITLE
Gnome 40 compatibility

### ISSUE THREAD

**Issue by geodro** [satran/fullscreenworkspace-satran.in#2]
Hello,

The extension is not compatible with Gnome 40

**Comment by satran** [comment]
Thanks, I wont be able to work on this for a few months unfortunately. But willing to accept fixes :)

**Comment by koriwi** [comment]
https://github.com/satran/fullscreenworkspace-satran.in/pull/4

**Comment by satran** [comment]
@geodro fixed with #4 .
