### ISSUE TITLE
New workspace with maximising

### ISSUE THREAD

**Issue by carallo** [satran/fullscreenworkspace-satran.in#7]
Sorry for opening another issue!

I was wondering if it would be possible to have the same behaviour but also with maximising windows, not just full screen (such as for videos or F11 in browsers)

**Comment by satran** [comment]
Hi @carallo. Thanks for opening the issue. I guess technically possible. I'll need some time to figure this out. I welcome pull requests :)

**Comment by carallo** [comment]
> Hi @carallo. Thanks for opening the issue. I guess technically possible. I'll need some time to figure this out. I welcome pull requests :)

Hi @satran, thank you so much for taking this into consideration! Unfortunately I have no programming skills, so I can't be helpful here, if I could I would for sure. I will wait in hope, if not, no worries ;)

Thank you again anyway! :)

**Comment by satran** [comment]
Hi @carallo with https://github.com/satran/fullscreenworkspace-satran.in/commit/f1bc51c172e27f452e90f768c02659f18d916dcf this can be set optionally now. I will upload the extension. Let me know if it works. I have only been able to test it on GNOME 41. Other versions I'm not too sure. Appreciate the request :)

**Comment by carallo** [comment]
Hi @satran, I just tested it and it works perfectly (I'm also on GNOME 41), amazing! This helps my workflow a lot.

Thank you so so much for this, really!
